# Generated by Django 2.2 on 2019-04-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Griferia', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=1)),
                ('nombre_item', models.CharField(default='grifo', max_length=200)),
                ('precio_unitario', models.IntegerField(default=1)),
                ('cantidad_stock', models.IntegerField(default=1)),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.TipoItem')),
            ],
        ),
    ]
