# Generated by Django 2.2 on 2019-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad_stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_unitario',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
