# Generated by Django 2.2 on 2019-04-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20190406_1317'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoitem',
            table='TipoItem',
        ),
    ]
