# Generated by Django 2.2 on 2019-04-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20190406_1532'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoitem',
            table=None,
        ),
    ]
